In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/data.csv')
df

crop  moisture  temp  pump
0    cotton       638    16     1
1    cotton       522    18     1
2    cotton       741    22     1
3    cotton       798    32     1
4    cotton       690    28     1
..      ...       ...   ...   ...
195  cotton       941    13     1
196  cotton       902    45     1
197  cotton       894    42     1
198  cotton      1022    45     1
199  cotton       979    10     1

[200 rows x 4 columns]

In [3]:
df.isna().sum()

crop        0
moisture    0
temp        0
pump        0
dtype: int64

In [4]:
df.columns

Index(['crop', 'moisture', 'temp', 'pump'], dtype='object')

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['crop']=le.fit_transform(df['crop'])
df


crop  moisture  temp  pump
0       0       638    16     1
1       0       522    18     1
2       0       741    22     1
3       0       798    32     1
4       0       690    28     1
..    ...       ...   ...   ...
195     0       941    13     1
196     0       902    45     1
197     0       894    42     1
198     0      1022    45     1
199     0       979    10     1

[200 rows x 4 columns]

In [6]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

**CREATING MODEL OF KNN,NB,SVM TOGETHER**

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
knn=KNeighborsClassifier(n_neighbors=7)
model_nb=GaussianNB()
model_svm=SVC()
lst=[knn,model_nb,model_svm]   #creating list with obj of 3 models

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
for i in lst:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("*****************************************************")
  print(accuracy_score(y_pred,y_test))
  print(confusion_matrix(y_test,y_pred))
  print(classification_report(y_test,y_pred))

*****************************************************
0.9666666666666667
[[13  2]
 [ 0 45]]
              precision    recall  f1-score   support

           0       1.00      0.87      0.93        15
           1       0.96      1.00      0.98        45

    accuracy                           0.97        60
   macro avg       0.98      0.93      0.95        60
weighted avg       0.97      0.97      0.97        60

*****************************************************
0.9666666666666667
[[13  2]
 [ 0 45]]
              precision    recall  f1-score   support

           0       1.00      0.87      0.93        15
           1       0.96      1.00      0.98        45

    accuracy                           0.97        60
   macro avg       0.98      0.93      0.95        60
weighted avg       0.97      0.97      0.97        60

*****************************************************
0.9833333333333333
[[14  1]
 [ 0 45]]
              precision    recall  f1-score   support

           0   